'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class recepty
    Public Property idreceptu As Integer
    Public Property vyrobek As Integer
    Public Property suroviny As String
    Public Property doba As Integer
    Public Property vyzkum As Integer

    Public Overridable Property veci As veci

End Class
