'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class veci
    Public Property idveci As Integer
    Public Property nazev As String
    Public Property typ As String
    Public Property vykon As Integer
    Public Property spotreba As Integer
    Public Property socket As String
    Public Property sloty As String
    Public Property popis As String

    Public Overridable Property recepties As ICollection(Of recepty) = New HashSet(Of recepty)

End Class
